#@data/values
---
scan_code_net:
  sonar:
   organisation: covergo
   project:  CoverGo_Auth
   token:  ${{ secrets.SONAR_TOKEN }}
  github_token: ${{ secrets.GITHUB_TOKEN }}
  coverlet_settings_file:  coverlet.runsettings
  test_project:  test/Test.My.Project.csproj
  #optional
  dotnet_frameworks:
    - version: 5.0
      prerelease: false
    - version: 6.0.x
      prerelease: true
  timeout: 5
  #optional
  git:
    branches:
      - master
      - main
      - F/*
      - f/*
      - R/*
      - r/*
      - B/*
      - b/*

    
    
